### ISSUE TITLE
Powering device from external source

### ISSUE THREAD

**Issue by OXOTHuK1976** [Xinyuan-LilyGO/T-Display-S3#51]
How to power board from external 5v source? Tried  battery connector but no succes.  It only powering from type-c

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/202943056-69de1aba-bb2c-4fac-88b1-75373cff1a0c.png)
From here the port can be powered with 5V.

**Comment by OXOTHuK1976** [comment]
Thats not work,  external 5v does not power device from this pin. Get 0.05A  but not started.   So, it is broken board?

**Comment by mmMicky** [comment]
I used the 5V and GND on the Raspberry Pi to connect to the board and it can be successfully lit.

**Comment by OXOTHuK1976** [comment]
Ok, seems my board is broken,  I used 5v from laboratory power source and from usb, nothing happen. 
Thank you and good luck.

**Comment by mmMicky** [comment]
![image](https://user-images.githubusercontent.com/63094275/202975998-68dade70-e785-4262-ab21-97aacf731438.png)
Not necessarily damage. There is a PWR_EN label here on the schematic. It is controlled by either USB or GPIO. You need to make sure you have this pin high.

**Comment by OXOTHuK1976** [comment]
Ok, thank you.  Im not strong in schematic.  Which pin I need pull up?  Or I need find this diode on board and pullup here?

**Comment by mmMicky** [comment]
This label corresponds to GPIO15. You need to set this to high.

**Comment by OXOTHuK1976** [comment]
Can`t find this pin on board. On your image it is LCD_POWER_ON,   but can`t find it physically.

**Comment by mmMicky** [comment]
It is not drawn externally. Only inside the board.

**Comment by OXOTHuK1976** [comment]
Thank you for your help. 
Finally crack the screen.  So question is not actual any more :)))
PS:  To everyone - be careful. The screen is very fragile, it cracked when I tried to insert the device into the breadboard.

**Comment by wiegleyj** [comment]
I wish this was better documented.

For those that don't know. The pull-up/down state of GPIO pins is persistent when power is removed.

So, if you do:

```
  //For esp-idf programming
  #define PWR_EN 15
  gpio_reset_pin(PWR_EN);
```
and run that code sequence once while powered from the USB cable. This will do the trick permanently as the esp32 maintains its pullup state when power is removed. the gpio_reset_pin disconnects the GPIO from both input and output but does enable the pullup resistor on it (from docs: select gpio function, enable pullup and disable input and output).

Not sure of the code sequence on arduino programming for esp32. But I think `pinMode(15, INPUT_PULLUP);` will do. Otherwise you'll need to go through the `gpio_config` functionality.

In any case, any thing you do to cause the ESP32 chip to enable its pullup resistor on GPIO15 will be persistent across power cycles unless you change/select a different pullup configuration for that pin.

**Comment by doh38** [comment]
> quence once while powered from the USB cable. This will do the trick permanently as the esp32 maintains its pullup state when power is removed. the gpio_reset_pin disconnects the GPIO from both input and output but does enable the pullup resistor on it (from docs: select gpio function, enable pullup and disable input and output).
> 
> Not sure of the code sequence on arduino programming for esp32. But I think `pinMode(15, INPUT_PULLUP);` will do. Otherwise you'll need to go through the `gpio_config` functionality.
> 
> In any case, any thing you do to cause the ESP32 chip to enable its pullup resistor on GPIO15 will be persistent across power cycles unless you change/select a different pullup configuration for that pin.

Thanks, it indeed works perfectly on arduino with the line you gave. one needs to put in in the setup(), but that's not a surprise :)

Now the 1000000$ question... what happens then when usb is powered and ext 5V too? also does this charge the battery? Asking before toasting my board :)
