### ISSUE TITLE
Library don't work in Arduino IDE (2.0.3)

### ISSUE THREAD

**Issue by laverdanny** [Xinyuan-LilyGO/T-Display-S3#98]
and example/factory/factory.ino need unknown #include "TouchLib.h" (several are possible, maybe a special one ?)

**Comment by teastainGit** [comment]
and it's here:
https://github.com/Xinyuan-LilyGO/T-Display-S3/tree/main/lib/TouchLib/src

**Comment by laverdanny** [comment]
I see, thanks !
any way to correctly install [T-Display-S3] library in Arduino ?
 several examples fails to compile and/or run once downloaded

And choosing communication port, Arduino IDE shows ESP32C3 Dev module instead of ESP32S3

**Comment by teastainGit** [comment]
I had a lot of trouble getting the LilyGO T-Display S3 to work, so I made a repository that just kept getting bigger and bigger.
https://github.com/teastainGit/LilyGO-T-display-S3-setup-and-examples
I say bigger because it is a lot of reading, but it will get you going with stable examples...you can branch out from there.
Arduino V2.0.3 is very good and it now seems to save the upload settings but it will switch boards on you sometimes. Just a bug, I suppose.
-Terry

**Comment by laverdanny** [comment]
Actually you're right, board name keep changing !
Thanks ! going to read a lot ;-)

**Comment by Felixrising** [comment]
Really the examples need reworking. Thanks teastainGit for your repo. Lots of issues with the board definition and libraries/examples not working or being a bit too brittle to reliably use. This repo needs rework! Quite a frustrating experience for a novice. :/

**Comment by lewisxhe** [comment]
If you still have problems, please restart
